### ISSUE TITLE
Add User Role header

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog-plugin-auth-sso#13]
Please add a User Role Header like
X-Remote-Role

**Comment by jhaar** [comment]
It really needs to be X-Remote-Role* - so that multiple roles can be passed through. Putting all the Roles as the values to one header sounds good - but I don't think anyone would be able to do that with standard Apache rewrite rules?

eg today we have people logging in via LDAP who are in >1 group - so they end up with multiple Roles. 
We want to use mod_mellon and it passes SAML groupmembership through as pseudo "arrays", 

MELLON_memberof_0 
MELLON_memberof_1
MELLON_memberof_2

so I'd use Apache's "RequestHeader set X-MELLON_memberof_0 "%{MELLON_memberof_0}e" to pass '0' through, and do more "set" commands for n=1,2,3,4... - which would enable me to map the first 'n' Roles. Very kludgy of course - but I'd gain the benefit of SAML - which is more appropriate for our environment than LDAP

**Comment by anrub** [comment]
@runningman84 @jhaar @kroepke Would you be so kind, and take a look at the PR, if that looks sufficient and conformant to you. Unfortunately the CI fails with some host not found error, that I'm not able to solve.

**Comment by runningman84** [comment]
It looks fine from my point of view!

**Comment by TheRealKingS** [comment]
Any updates here?

**Comment by mwysokin** [comment]
I believe it's a really wanted feature. We are waiting for it too.

**Comment by joschi** [comment]
@mwysokin Would you be willing to sponsor the development of this feature?

**Comment by anrub** [comment]
@joschi Please take a look at the #25  - I already developed this, @kroepke is assigned to review this task or is sponsoring something different?

**Comment by TheRealKingS** [comment]
In the meantime I have built the plugin manually. For this I took the codebase of version 2.3.0 and adopted the customization of @anrub. It runs without problems.

**Comment by anrub** [comment]
@joschi @kroepke what can I do to help with the integration? Thank you

**Comment by TheRealKingS** [comment]
A small feedback: If a new user is created after the login with shibboleth, then ther is a /%/ at the end of the URL. Bug?

**Comment by anrub** [comment]
I don't think, that this can be done by this change. You could log/watch the URLs in the chrome network tab, to see how the redirecting is done and which component is redirecting.

**Comment by kroepke** [comment]
This has now been merged at released as 2.5.0: https://github.com/Graylog2/graylog-plugin-auth-sso/releases/tag/2.5.0
